---

- name: icingaweb modules
  block:
    - name: create local temp directory
      become: false
      delegate_to: localhost
      file:
        path: "{{ icingaweb_local_tmp_directory }}/icingaweb_modules/"
        state: directory
        mode: 0770

    - name: download external module to local directory {{ icingaweb_local_tmp_directory }}/icingaweb_modules
      become: false
      delegate_to: localhost
      git:
        depth: 1 # copy the least bit of history possible to get that repo.
        repo: "{{ item.src }}"
        version: "{{ item.version | default(omit) }}"
        dest: "{{ icingaweb_local_tmp_directory }}/icingaweb_modules/{{ item.name }}"
        update: true
      loop:
        "{{ icingaweb_external_modules }}"
      loop_control:
        label: "  module: {{ item.name }}  - version: {{ item.version | default('', true) }}"

    - name: create transfer archive
      become: false
      delegate_to: localhost
      archive:
        path: "{{ icingaweb_local_tmp_directory }}/icingaweb_modules"
        dest: "{{ icingaweb_local_tmp_directory }}/icingaweb_modules.tgz"
        mode: 0660

    - name: propagate icingaweb_modules.tgz
      become: true
      copy:
        src: "{{ icingaweb_local_tmp_directory }}/icingaweb_modules.tgz"
        dest: "/tmp/"
        mode: 0660

    - name: extract icingaweb_modules.tgz
      unarchive:
        src: "/tmp/icingaweb_modules.tgz"
        dest: /tmp/
        mode: 0660
        remote_src: true

    - name: copy modules in place '{{ icingaweb_install_dir }}/modules/'
      become: true
      copy:
        remote_src: true
        src: "/tmp/icingaweb_modules/{{ item.name }}/"
        dest: "{{ icingaweb_install_dir }}/modules/{{ item.name }}"
        owner: "{{ icingaweb_user }}"
        group: "{{ icingaweb_group }}"
        mode: 0755
      loop:
        "{{ icingaweb_external_modules }}"
      loop_control:
        label: "  module: {{ item.name }}  - version: {{ item.version | default('', true) }}"

    - name: fix rights for modules
      become: true
      file:
        path: "{{ icingaweb_install_dir }}/modules/{{ item.name }}"
        owner: "{{ icingaweb_user }}"
        group: "{{ icingaweb_group }}"
        mode: 0755
        recurse: true
      loop:
        "{{ icingaweb_external_modules }}"
      loop_control:
        label: "  module: {{ item.name }}  - version: {{ item.version | default('', true) }}"

    - name: create directory for module configuration
      become: true
      file:
        path: /etc/icingaweb2/modules/{{ item.name }}
        state: directory
        recurse: true
        owner: "{{ icingaweb_user }}"
        group: "{{ icingaweb_group }}"
        mode: 0755
      loop:
        "{{ icingaweb_external_modules }}"
      loop_control:
        label: "  module: {{ item.name }}  - version: {{ item.version | default('', true) }}"
      when:
        - item.enabled
        - item.configuration is defined
        - item.configuration | count > 0

    - name: configure module
      become: true
      template:
        src: modules/{{ item.name }}/config.ini.j2
        dest: /etc/icingaweb2/modules/{{ item.name }}/config.ini
        owner: "{{ icingaweb_user }}"
        group: "{{ icingaweb_group }}"
        mode: 0666
      loop:
        "{{ icingaweb_external_modules }}"
      loop_control:
        label: "  module: {{ item.name }}  - version: {{ item.version | default('', true) }}"
      when:
        - item.enabled
        - item.configuration is defined
        - item.configuration | count > 0

    - name: create grafanas graphs.ini
      become: true
      template:
        src: modules/{{ item.name }}/graphs.ini.j2
        dest: /etc/icingaweb2/modules/{{ item.name }}/graphs.ini
        owner: "{{ icingaweb_user }}"
        group: "{{ icingaweb_group }}"
        mode: 0666
      loop:
        "{{ icingaweb_external_modules }}"
      loop_control:
        label: "  module: {{ item.name }}  - version: {{ item.version | default('', true) }}"
      when:
        - item.enabled
        - item.name == 'grafana'
        - item.configuration is defined
        - item.configuration | count > 0
        - item.graphs is defined
        - item.graphs | count > 0

    - name: disable modules
      become: true
      icingaweb_module:
        state: absent
        module: "{{ item.name }}"
      loop:
        "{{ icingaweb_external_modules }}"
      loop_control:
        label: "  module: {{ item.name }}  - version: {{ item.version | default('', true) }}"
      when:
        - not item.enabled | bool | default('false')

    - name: enable modules
      become: true
      icingaweb_module:
        state: present
        module: "{{ item.name }}"
      loop:
        "{{ icingaweb_external_modules }}"
      loop_control:
        label: "  module: {{ item.name }}  - version: {{ item.version | default('', true) }}"
      when:
        - item.enabled | bool | default('false')

  when:
    - icingaweb_external_modules is defined
    - icingaweb_external_modules | flatten(1) | count > 0

...
