---

icingaweb_log_level: WARN

icingaweb_resources:
  icingaweb:
    type: db
    db: mysql
    host: database
    port: 3306
    dbname: icingaweb_config
    username: icingaweb_config
    password: icingaweb_config
    prefix: icingaweb_
    charset: utf8
  icinga_ido:
    type: db
    db: mysql
    host: database
    port: 3306
    dbname: icinga2_ido
    username: icinga2_ido
    password: icinga2
    charset: utf8

icingaweb_auth_backend:
  database:
    host: database
    port: 3306
    dbname: icingaweb_config
    username: icingaweb_config
    password: icingaweb_config

icingaweb_commandtransport:
  master-1:
    transport: api
    host: icinga
    port: 5665
    username: icingaweb
    password: S0mh1TuFJI

icingaweb_users:
  - admin:
    username: admin
    password: admin
    # force: true
    preferences:
      language: de_DE
      timezone: Europe/Berlin
      show_application_state_messages: false
      show_stacktraces: false
      show_benchmark: false
      auto_refresh: true
  - bodsch:
    username: bodsch
    password: xxx
  - dark:
    username: dark
    password: s3cur3

icingaweb_themes:
  - unicorn:
    name: unicorn
    src: https://github.com/Mikesch-mp/icingaweb2-theme-unicorn.git
    version: v1.0.2
    image: { name: "unicorn.png", "url": "http://i.imgur.com/SCfMd.png" }
    enabled: true
  - batman-dark:
    name: batman-dark
    src: https://github.com/jschanz/icingaweb2-theme-batman-dark.git
    version: v1.0.0
    enabled: false

icingaweb_themes_default: Icinga

icingaweb_external_modules:
  - audit:
    enabled: true
    name: audit
    src: https://github.com/Icinga/icingaweb2-module-audit.git
    version: v1.0.1

...
